[package]
name = "transgender-init"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
os-release = "0.1.0"
nix = "0.27.1"
bson = "2.8.1"
zstd = "0.13.0"
rayon = "1.8.0"
