// init-driver.rs - The init system driver.
// Copyright (c) 2023-2024 Kıvılcım Leyla Öztürk.
// Licensed under the MIT License <http://opensource.org/licenses/MIT>

// holds the source code for the main init driver.
pub mod driver {
    // import the necessary libraries for self PID checking.
    use std::process;

    // also, cutie, don't forget to load /etc/os-release
    // and print the OS name and version on the screen.
    // we are going to use the os-release crate for that.
    // import the necessary libraries for os-release.
    use os_release::OsRelease;

    // immport the necessary functions for reading files.
    use std::fs::File;
    use std::io::prelude::*;

    // import the functions for delaying the execution.
    use std::thread;
    use std::time::Duration;

    // import the necessary libraries for self PID checking.
    use std::process;

    // also, cutie, don't forget to load /etc/os-release
    // and print the OS name and version on the screen.
    // we are going to use the os-release crate for that.
    // import the necessary libraries for os-release.
    use os_release::OsRelease;

    // immport the necessary functions for reading files.
    use std::fs::File;
    use std::io::prelude::*;

    // import the functions for delaying the execution.
    use std::thread;
    use std::time::Duration;

    // import the necessary libraries for self PID checking.
    use std::process;

    // import the os-release handler.
    use os_release::OsRelease;

    /// Arguments for init. These are the target name, the rootfs,
    /// the command line arguments, the path of the init corpus,
    /// (generated by Androgen during the execution of Estrogen)
    /// and the other kernel arguments.
    pub struct InitArgs {
        pub target_name: String,
        pub rootfs: String,
        pub cmdline: String,
        pub init_corpus: String,
        pub kernel_args: Vec<String>,
    }
}